# Github Project 1

## EDA

In [413]:
import pandas as pd

In [414]:
df = pd.read_csv(r'..\data\booking_reviews copy.csv')

In [415]:
df.head()

,index,review_title,reviewed_at,reviewed_by,images,crawled_at,url,hotel_name,hotel_url,avg_rating,nationality,rating,review_text,raw_review_text,tags,meta
0,0,Exceptional,11 July 2021,Kyrylo,NaN,"07/20/2021, 01:09:27",https://www.booking.com/reviews/be/hotel/villa...,Villa Pura Vida,https://www.booking.com/hotel/be/villa-pura-vi...,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...","<p class=""review_pos ""><svg aria-label=""Positi...",Business trip~Solo traveller~Junior Suite~Stay...,"{'language': 'en-gb', 'source': 'https://www.b..."
1,1,I highly recommend this b&b! We enjoyed it a lot!,24 November 2019,Dimitri,NaN,"07/20/2021, 01:09:27",https://www.booking.com/reviews/be/hotel/villa...,Villa Pura Vida,https://www.booking.com/hotel/be/villa-pura-vi...,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,"<p class=""review_pos ""><svg aria-label=""Positi...",Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,"{'language': 'en-gb', 'source': 'https://www.b..."
2,2,Exceptional,3 January 2020,Virginia,NaN,"07/20/2021, 01:09:27",https://www.booking.com/reviews/be/hotel/hydro...,Hydro Palace Apartment,https://www.booking.com/hotel/be/hydro-palace....,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,"<p class=""review_neg ""><svg aria-label=""Negati...",Leisure trip~Couple~Apartment with Sea View~St...,"{'language': 'en-gb', 'source': 'https://www.b..."
3,3,My stay in the house was a experiencing bliss ...,8 September 2019,Kannan,NaN,"07/20/2021, 01:09:28",https://www.booking.com/reviews/be/hotel/villa...,Villa Pura Vida,https://www.booking.com/hotel/be/villa-pura-vi...,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,"<p class=""review_pos ""><svg aria-label=""Positi...",Business trip~Solo traveller~Junior Suite~Stay...,"{'language': 'en-gb', 'source': 'https://www.b..."
4,4,One bedroom apartment with wonderful view and ...,23 June 2019,Sue,https://cf.bstatic.com/xdata/images/xphoto/squ...,"07/20/2021, 01:09:28",https://www.booking.com/reviews/be/hotel/hydro...,Hydro Palace Apartment,https://www.booking.com/hotel/be/hydro-palace....,9.2,South Africa,9.2,The building itself has a very musty smell in ...,"<p class=""review_neg ""><svg aria-label=""Negati...",Leisure trip~People with friends~Apartment wit...,"{'language': 'en-gb', 'source': 'https://www.b..."

In [416]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26675 entries, 0 to 26674
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            26675 non-null  int64
 1   review_title     26674 non-null  str
 2   reviewed_at      26570 non-null  str
 3   reviewed_by      26570 non-null  str
 4   images           938 non-null    str
 5   crawled_at       26386 non-null  str
 6   url              26386 non-null  str
 7   hotel_name       26386 non-null  str
 8   hotel_url        26386 non-null  str
 9   avg_rating       26386 non-null  float64
 10  nationality      26370 non-null  str
 11  rating           26386 non-null  float64
 12  review_text      26386 non-null  str
 13  raw_review_text  26202 non-null  str
 14  tags             26202 non-null  str
 15  meta             26202 non-null  str
dtypes: float64(2), int64(1), str(13)
memory usage: 3.3 MB

In [417]:
df.shape

(26675, 16)

In [418]:
df["language"] = df["meta"].str.extract(r"'language':\s*'([^']+)'")

In [419]:
columns_to_drop = ['index','reviewed_by','images','crawled_at','url','hotel_url','raw_review_text','meta']
df = df.drop(columns_to_drop, axis=1)
df.head()

,review_title,reviewed_at,hotel_name,avg_rating,nationality,rating,review_text,tags,language
0,Exceptional,11 July 2021,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",Business trip~Solo traveller~Junior Suite~Stay...,en-gb
1,I highly recommend this b&b! We enjoyed it a lot!,24 November 2019,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,en-gb
2,Exceptional,3 January 2020,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,Leisure trip~Couple~Apartment with Sea View~St...,en-gb
3,My stay in the house was a experiencing bliss ...,8 September 2019,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,Business trip~Solo traveller~Junior Suite~Stay...,en-gb
4,One bedroom apartment with wonderful view and ...,23 June 2019,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,Leisure trip~People with friends~Apartment wit...,en-gb

In [420]:
df.shape

(26675, 9)

In [421]:
df.isnull().sum()

review_title      1
reviewed_at     105
hotel_name      289
avg_rating      289
nationality     305
rating          289
review_text     289
tags            473
language        473
dtype: int64

In [422]:
df = df.dropna()
df.shape

(26185, 9)

In [423]:
df.isnull().sum()

review_title    0
reviewed_at     0
hotel_name      0
avg_rating      0
nationality     0
rating          0
review_text     0
tags            0
language        0
dtype: int64

In [424]:
df.head()

,review_title,reviewed_at,hotel_name,avg_rating,nationality,rating,review_text,tags,language
0,Exceptional,11 July 2021,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",Business trip~Solo traveller~Junior Suite~Stay...,en-gb
1,I highly recommend this b&b! We enjoyed it a lot!,24 November 2019,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,en-gb
2,Exceptional,3 January 2020,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,Leisure trip~Couple~Apartment with Sea View~St...,en-gb
3,My stay in the house was a experiencing bliss ...,8 September 2019,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,Business trip~Solo traveller~Junior Suite~Stay...,en-gb
4,One bedroom apartment with wonderful view and ...,23 June 2019,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,Leisure trip~People with friends~Apartment wit...,en-gb

In [425]:
df.info()

<class 'pandas.DataFrame'>
Index: 26185 entries, 0 to 26674
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_title  26185 non-null  str
 1   reviewed_at   26185 non-null  str
 2   hotel_name    26185 non-null  str
 3   avg_rating    26185 non-null  float64
 4   nationality   26185 non-null  str
 5   rating        26185 non-null  float64
 6   review_text   26185 non-null  str
 7   tags          26185 non-null  str
 8   language      26185 non-null  str
dtypes: float64(2), str(7)
memory usage: 2.0 MB

In [426]:
df['date'] = pd.to_datetime(df['reviewed_at'], format='%d %B %Y')

df['year'] = df['date'].dt.year.astype(str)
df['month'] = df['date'].dt.strftime('%B')

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

df['season'] = df['date'].dt.month.apply(get_season)

month_order = ['January','February','March','April','May','June',
               'July','August','September','October','November','December']
df['month'] = pd.Categorical(df['month'], categories=month_order, ordered=True)

In [427]:
df.head()

,review_title,reviewed_at,hotel_name,avg_rating,nationality,rating,review_text,tags,language,date,year,month,season
0,Exceptional,11 July 2021,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2021-07-11,2021,July,Summer
1,I highly recommend this b&b! We enjoyed it a lot!,24 November 2019,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,en-gb,2019-11-24,2019,November,Autumn
2,Exceptional,3 January 2020,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,Leisure trip~Couple~Apartment with Sea View~St...,en-gb,2020-01-03,2020,January,Winter
3,My stay in the house was a experiencing bliss ...,8 September 2019,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2019-09-08,2019,September,Autumn
4,One bedroom apartment with wonderful view and ...,23 June 2019,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,Leisure trip~People with friends~Apartment wit...,en-gb,2019-06-23,2019,June,Summer

In [428]:
df = df.drop(['reviewed_at'],axis=1)

In [429]:
df.head()

,review_title,hotel_name,avg_rating,nationality,rating,review_text,tags,language,date,year,month,season
0,Exceptional,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2021-07-11,2021,July,Summer
1,I highly recommend this b&b! We enjoyed it a lot!,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,en-gb,2019-11-24,2019,November,Autumn
2,Exceptional,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,Leisure trip~Couple~Apartment with Sea View~St...,en-gb,2020-01-03,2020,January,Winter
3,My stay in the house was a experiencing bliss ...,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2019-09-08,2019,September,Autumn
4,One bedroom apartment with wonderful view and ...,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,Leisure trip~People with friends~Apartment wit...,en-gb,2019-06-23,2019,June,Summer

In [430]:
df.iloc[0,6]

'Business trip~Solo traveller~Junior Suite~Stayed 1 night~Submitted via mobile'

In [431]:
df.head()

,review_title,hotel_name,avg_rating,nationality,rating,review_text,tags,language,date,year,month,season
0,Exceptional,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2021-07-11,2021,July,Summer
1,I highly recommend this b&b! We enjoyed it a lot!,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,en-gb,2019-11-24,2019,November,Autumn
2,Exceptional,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,Leisure trip~Couple~Apartment with Sea View~St...,en-gb,2020-01-03,2020,January,Winter
3,My stay in the house was a experiencing bliss ...,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2019-09-08,2019,September,Autumn
4,One bedroom apartment with wonderful view and ...,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,Leisure trip~People with friends~Apartment wit...,en-gb,2019-06-23,2019,June,Summer

In [432]:
df.shape

(26185, 12)

In [433]:
df['tags'].to_list()

['Business trip~Solo traveller~Junior Suite~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Suite~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Apartment with Sea View~Stayed 6 nights~Submitted via mobile',
 'Business trip~Solo traveller~Junior Suite~Stayed 4 nights~Submitted via mobile',
 'Leisure trip~People with friends~Apartment with Sea View~Stayed 4 nights~Submitted via mobile',
 'Business trip~Couple~Junior Suite~Stayed 1 night~Submitted via mobile',
 'Business trip~Couple~Deluxe Double Room with Bath~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Family with young children~Four-Bedroom House~Stayed 7 nights~Submitted via mobile',
 'Leisure trip~Couple~Apartment with Sea View~Stayed 3 nights~Submitted via mobile',
 'Business trip~Group~Deluxe Suite~Stayed 1 night',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~People with friends~Four-Bedroom House~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~People with friends~Suite~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Solo traveller~Deluxe Studio~Stayed 1 night',
 'Business trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 6 nights',
 'Business trip~Solo traveller~Standard Double Room~Stayed 2 nights',
 'Leisure trip~Couple~Junior Suite~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Family with young children~Four-Bedroom House~Stayed 7 nights',
 'Leisure trip~Couple~Design Room~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Studio~Stayed 3 nights',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~King Suite with Bathtub~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Family with young children~Four-Bedroom House~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Comfort Room~Stayed 1 night',
 'Couple~Deluxe Double Studio~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Solo traveller~Standard Double Room~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Suite~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 1 night',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Basic Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Comfort Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Family with young children~Deluxe Studio~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room~Stayed 1 night',
 'Business trip~Group~Deluxe Suite~Stayed 4 nights',
 'Leisure trip~Family with young children~Double Room~Stayed 1 night',
 'Leisure trip~Couple~One-Bedroom Apartment~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Double Room with Bath~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Solo traveller~Standard Double or Twin Room~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Wonderful Room with Spa Bath~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Double Room with Private Bathroom~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Comfort Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Studio~Stayed 3 nights',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 1 night',
 'Leisure trip~Family with young children~Duplex Apartment (4 Adults)~Stayed 2 nights',
 'Leisure trip~Couple~King Suite with Bathtub~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Double Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Group~One-Bedroom Apartment~Stayed 2 nights',
 'Business trip~Solo traveller~Deluxe Double Room with Bath~Stayed 1 night~Submitted via mobile',
 'Business trip~Family with young children~Deluxe Apartment~Stayed 3 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Single Room~Stayed 1 night',
 'Leisure trip~Couple~Basic Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 4 nights',
 'Leisure trip~Family with young children~Double Room with Private Bathroom~Stayed 1 night',
 'Leisure trip~Family with young children~Design Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Superior Double Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room~Stayed 3 nights~Submitted via mobile',
 'Business trip~Couple~Deluxe Suite~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Solo traveller~Single Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~One-Bedroom Apartment~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Solo traveller~Deluxe Double Room with Bath~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Chalet~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~People with friends~Deluxe Apartment~Stayed 4 nights~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Double Room~Stayed 1 night',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~People with friends~Double Room with Private Bathroom~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Comfort Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Double Studio~Stayed 1 night',
 'Leisure trip~Solo traveller~Superior Double Room~Stayed 3 nights',
 'Leisure trip~Couple~Standard Double Room~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Suite~Stayed 3 nights~Submitted via mobile',
 'Business trip~Solo traveller~One-Bedroom Apartment (2 Adults)~Stayed 1 night',
 'Leisure trip~Group~One-Bedroom Apartment~Stayed 1 night',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 3 nights',
 'Business trip~Solo traveller~Chalet~Stayed 3 nights',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 5 nights',
 'Leisure trip~People with friends~Standard Double or Twin Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Basic Room~Stayed 1 night',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 3 nights',
 'Leisure trip~Couple~Double Room with Private Bathroom~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Design Room~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Superior Double Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Duplex Apartment (4 Adults)~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Solo traveller~Junior Suite~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Double Room~Stayed 1 night',
 'Leisure trip~Family with young children~One-Bedroom Apartment~Stayed 3 nights',
 'Leisure trip~Solo traveller~Deluxe Double Room with Bath~Stayed 4 nights~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Apartment~Stayed 3 nights',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 1 night',
 'Couple~Wonderful Room with Spa Bath~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Comfort Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Double Studio~Stayed 1 night',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Duplex Apartment (4 Adults)~Stayed 2 nights',
 'Business trip~Solo traveller~Junior Suite~Stayed 1 night',
 'Leisure trip~Couple~One-Bedroom Apartment (2 Adults)~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Family with young children~One-Bedroom Apartment~Stayed 1 night',
 'Business trip~Solo traveller~Deluxe Double Room with Bath~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 8 nights',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Basic Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Family with young children~Comfort Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Apartment~Stayed 5 nights~Submitted via mobile',
 'Business trip~Solo traveller~Superior Double Room with Sofa Bed~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room~Stayed 1 night',
 'Business trip~Solo traveller~Deluxe Suite~Stayed 1 night',
 'Leisure trip~Group~One-Bedroom Apartment (2 Adults)~Stayed 2 nights',
 'Leisure trip~Family with young children~One-Bedroom Apartment~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 2 nights',
 'Leisure trip~Family with young children~Standard Double or Twin Room~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Sweet Room~Stayed 1 night',
 'Business trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Junior Suite~Stayed 1 night',
 'Leisure trip~Solo traveller~Deluxe Studio~Stayed 2 nights',
 'Business trip~People with friends~Superior Double Room~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Family with young children~Duplex Apartment (4 Adults)~Stayed 2 nights',
 'Business trip~Solo traveller~Deluxe Suite~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Double Room~Stayed 1 night',
 'Leisure trip~Family with young children~One-Bedroom Apartment~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 2 nights',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 3 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double or Twin Room~Stayed 3 nights',
 'Business trip~Solo traveller~Basic Room~Stayed 1 night',
 'Business trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights',
 'Leisure trip~Family with young children~Comfort Room~Stayed 2 nights',
 'Business trip~Solo traveller~Deluxe Double Studio~Stayed 1 night',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 1 night',
 'Solo traveller~Standard Double Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Suite~Stayed 1 night',
 'Leisure trip~Couple~Double Room~Stayed 7 nights',
 'Leisure trip~Family with young children~One-Bedroom Apartment~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 1 night',
 'Business trip~Group~Deluxe Apartment~Stayed 4 nights~Submitted via mobile',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Basic Room~Stayed 1 night',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~People with friends~Junior Suite~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Group~Deluxe Apartment~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Superior Double Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room~Stayed 1 night',
 'Leisure trip~Couple~Junior Suite~Stayed 1 night',
 'Leisure trip~Couple~Double Room~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~One-Bedroom Apartment~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Double Room with Bath~Stayed 1 night~Submitted via mobile',
 'Business trip~Couple~Deluxe Apartment~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 1 night',
 'Leisure trip~Couple~Basic Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Solo traveller~Comfort Room~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Family with young children~Deluxe Studio~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 2 nights',
 'Business trip~Solo traveller~Standard Double Room~Stayed 1 night',
 'Leisure trip~Family with young children~Deluxe Suite~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Double Room~Stayed 1 night',
 'Leisure trip~Couple~One-Bedroom Apartment~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Apartment~Stayed 26 nights',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 2 nights',
 'Leisure trip~Couple~Basic Room~Stayed 1 night',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Comfort Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Solo traveller~Superior Double Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Group~Deluxe Suite~Stayed 1 night',
 'Business trip~Solo traveller~Double Room~Stayed 1 night',
 'Leisure trip~Group~One-Bedroom Apartment~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Family with young children~Wonderful Room with Spa Bath~Stayed 3 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights',
 'Business trip~Group~Design Room~Stayed 1 night',
 'Business trip~Solo traveller~Deluxe Apartment~Stayed 2 nights',
 'Leisure trip~Family with young children~Superior Double Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room~Stayed 3 nights',
 'Leisure trip~Couple~Deluxe Suite~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Double Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Family with young children~One-Bedroom Apartment~Stayed 1 night',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 4 nights',
 'Leisure trip~Couple~Junior Suite~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Solo traveller~Basic Room~Stayed 1 night',
 'Leisure trip~Group~Standard Double Room with Shared Bathroom~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Comfort Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Superior Double Room~Stayed 3 nights',
 'Leisure trip~Group~Duplex Apartment (4 Adults)~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Solo traveller~Junior Suite~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Deluxe Suite~Stayed 2 nights',
 'Leisure trip~People with friends~Deluxe Apartment~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Family with young children~Basic Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 7 nights~Submitted via mobile',
 'Leisure trip~Family with young children~Junior Suite~Stayed 2 nights',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Duplex Apartment (4 Adults)~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Double Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~People with friends~Deluxe Apartment~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Deluxe Double Room~Stayed 2 nights',
 'Leisure trip~Solo traveller~Basic Room~Stayed 2 nights~Submitted via mobile',
 'Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Solo traveller~Comfort Room~Stayed 2 nights',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 2 nights',
 'Business trip~Solo traveller~Standard Double Room~Stayed 2 nights',
 'Business trip~Group~Deluxe Suite~Stayed 2 nights',
 'Leisure trip~Couple~Deluxe Apartment~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Basic Room~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Family with young children~Comfort Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Superior Double Room~Stayed 2 nights',
 'Leisure trip~Solo traveller~Standard Double Room~Stayed 2 nights',
 'Leisure trip~Couple~One-Bedroom Apartment (2 Adults)~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Standard Double or Twin Room~Stayed 3 nights~Submitted via mobile',
 'Leisure trip~Couple~Brilliant Room with Spa Bath~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights',
 'Leisure trip~Couple~Design Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Superior Double Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double Room~Stayed 1 night',
 'Business trip~Solo traveller~Single Room~Stayed 2 nights',
 'Business trip~Solo traveller~Standard Double or Twin Room~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Basic Room~Stayed 1 night',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 2 nights~Submitted via mobile',
 'Leisure trip~Couple~Comfort Room~Stayed 4 nights~Submitted via mobile',
 'Leisure trip~Family with young children~Superior Double Room with Sofa Bed~Stayed 2 nights',
 'Business trip~Solo traveller~Standard Double Room~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double or Twin Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Couple~Cozy Room~Stayed 1 night~Submitted via mobile',
 'Leisure trip~Solo traveller~Standard Double Room with Shared Bathroom~Stayed 4 nights~Submitted via mobile',
 'Leisure trip~Couple~Comfort Room~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Superior Double Room~Stayed 2 nights',
 'Group~Duplex Apartment (4 Adults)~Stayed 2 nights~Submitted via mobile',
 'Business trip~Solo traveller~Standard Studio~Stayed 19 nights~Submitted via mobile',
 'Leisure trip~People with friends~Deluxe Double Room with Shower~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Single Room~Stayed 1 night',
 'Leisure trip~Family with young children~Holiday Home~Stayed 3 nights',
 'Leisure trip~Family with young children~One-Bedroom House~Stayed 1 night',
 'Leisure trip~People with friends~Villa~Stayed 5 nights~Submitted via mobile',
 'Leisure trip~Couple~One-Bedroom Apartment (2 Adults)~Stayed 1 night~Submitted via mobile',
 'Business trip~Solo traveller~Standard Double or Twin Room~Stayed 1 night',
 'Leisure trip~Couple~Comfy Room~Stayed 1 night',

In [434]:
df['tags'].str.count('~').value_counts()

tags
4    16672
3     9331
2      129
5       53
Name: count, dtype: int64

In [385]:
def extract_tag(tags, keyword):
    for tag in tags.split('~'):
        if keyword.lower() in tag.lower():
            return tag.strip()
    return None

df['trip_type'] = df['tags'].apply(lambda x: extract_tag(x, 'trip'))
df['traveller_type'] = df['tags'].apply(lambda x: extract_tag(x, 'family') or extract_tag(x, 'solo') or extract_tag(x, 'couple') or extract_tag(x, 'group') or extract_tag(x, 'business'))
df['stay_length'] = df['tags'].apply(lambda x: extract_tag(x, 'night'))
df['submission_type'] = df['tags'].apply(lambda x: extract_tag(x, 'mobile') or extract_tag(x, 'desktop'))

In [ ]:
# split_df = df["tags"].str.split("~", expand=True)
# split_df.columns = ["trip_type", "traveller_type", "room_type", "stay_length", "submission_type", "extra"]
# split_df.head()

,trip_type,traveller_type,room_type,stay_length,submission_type,extra
0,Business trip,Solo traveller,Junior Suite,Stayed 1 night,Submitted via mobile,NaN
1,Leisure trip,Couple,Deluxe Suite,Stayed 1 night,Submitted via mobile,NaN
2,Leisure trip,Couple,Apartment with Sea View,Stayed 6 nights,Submitted via mobile,NaN
3,Business trip,Solo traveller,Junior Suite,Stayed 4 nights,Submitted via mobile,NaN
4,Leisure trip,People with friends,Apartment with Sea View,Stayed 4 nights,Submitted via mobile,NaN

In [386]:
df.head()

,review_title,hotel_name,avg_rating,nationality,rating,review_text,tags,language,date,year,month,season,trip_type,traveller_type,stay_length,submission_type
0,Exceptional,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2021-07-11,2021,July,Summer,Business trip,Solo traveller,Stayed 1 night,Submitted via mobile
1,I highly recommend this b&b! We enjoyed it a lot!,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,en-gb,2019-11-24,2019,November,Autumn,Leisure trip,Couple,Stayed 1 night,Submitted via mobile
2,Exceptional,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,Leisure trip~Couple~Apartment with Sea View~St...,en-gb,2020-01-03,2020,January,Winter,Leisure trip,Couple,Stayed 6 nights,Submitted via mobile
3,My stay in the house was a experiencing bliss ...,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2019-09-08,2019,September,Autumn,Business trip,Solo traveller,Stayed 4 nights,Submitted via mobile
4,One bedroom apartment with wonderful view and ...,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,Leisure trip~People with friends~Apartment wit...,en-gb,2019-06-23,2019,June,Summer,Leisure trip,NaN,Stayed 4 nights,Submitted via mobile

In [387]:
df['stay_length'].value_counts()

stay_length
Stayed 1 night      12568
Stayed 2 nights      7419
Stayed 3 nights      3561
Stayed 4 nights      1483
Stayed 5 nights       546
Stayed 6 nights       218
Stayed 7 nights       175
Stayed 8 nights        58
Stayed 9 nights        37
Stayed 10 nights       29
Stayed 12 nights       19
Stayed 11 nights       17
Stayed 14 nights       17
Stayed 13 nights        8
Stayed 26 nights        4
Stayed 16 nights        4
Stayed 20 nights        4
Stayed 30 nights        3
Stayed 15 nights        3
Stayed 19 nights        2
Stayed 21 nights        2
Stayed 17 nights        2
Stayed 28 nights        2
Stayed 25 nights        1
Stayed 22 nights        1
Stayed 27 nights        1
Stayed 18 nights        1
Name: count, dtype: int64

In [390]:
df['stay_length'].value_counts()

stay_length
Stayed 1 night      12568
Stayed 2 nights      7419
Stayed 3 nights      3561
Stayed 4 nights      1483
Stayed 5 nights       546
Stayed 6 nights       218
Stayed 7 nights       175
Stayed 8 nights        58
Stayed 9 nights        37
Stayed 10 nights       29
Stayed 12 nights       19
Stayed 11 nights       17
Stayed 14 nights       17
Stayed 13 nights        8
Stayed 26 nights        4
Stayed 16 nights        4
Stayed 20 nights        4
Stayed 30 nights        3
Stayed 15 nights        3
Stayed 19 nights        2
Stayed 21 nights        2
Stayed 17 nights        2
Stayed 28 nights        2
Stayed 25 nights        1
Stayed 22 nights        1
Stayed 27 nights        1
Stayed 18 nights        1
Name: count, dtype: int64

In [ ]:
# split_df['stay_length'].value_counts()

stay_length
Stayed 1 night          12066
Stayed 2 nights          7173
Stayed 3 nights          3468
Stayed 4 nights          1418
Submitted via mobile      731
                        ...
Stayed 18 nights            1
Budget Double Room          1
Budget Room                 1
Comfort Twin                1
Comfort Double              1
Name: count, Length: 94, dtype: int64

In [391]:
df['traveller_type'].value_counts()

traveller_type
Couple                                                  9437
Solo traveller                                          7189
Family with young children                              5034
Group                                                   2840
Business trip                                            124
Family Room                                               69
Family Studio                                             30
Family Room with Terrace                                  15
Family Suite                                              14
Comfort Family Room                                       11
Family Room with Bathroom                                 10
Family Cabin on Boat                                       9
Family Room with Private Bathroom                          8
Family Room with Partial Sea View                          8
Family Bungalow                                            7
Family Room with Garden View                               5
Deluxe Family Room                                         5
Family Room (4 Adults)                                     5
Family Room with Shower                                    4
Family Apartment (3 Adults) - E. Polotskoy Street, 1       4
Family Room (3 Adults + 2 Children)                        4
Family Room (2 Adults + 2 Children)                        3
Family Apartment semi duplex                               3
Family Room (5 Adults)                                     3
Family Room with Balcony                                   2
Standard Family Room                                       2
Family Double Room                                         2
Budget Family Room                                         2
Family Apartment (4 Adults)                                2
Superior Family Room                                       2
Family Room (6 Adults)                                     2
Duplex Quadruple Family Room                               1
Family Room with Bath                                      1
Business Double Room                                       1
Family Room (2 Adults + 1 Child)                           1
Connecting Family Room                                     1
Business Apartment                                         1
Name: count, dtype: int64

In [348]:
split_df['traveller_type'].to_list()

['Solo traveller',
 'Couple',
 'Couple',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Group',
 'Couple',
 'People with friends',
 'People with friends',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Deluxe Double Studio',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Couple',
 'Couple',
 'Group',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'People with friends',
 'Solo traveller',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Solo traveller',
 'Group',
 'Couple',
 'Solo traveller',
 'Couple',
 'People with friends',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Wonderful Room with Spa Bath',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'People with friends',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Standard Double Room',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Couple',
 'Group',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'People with friends',
 'Group',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Group',
 'Solo traveller',
 'Group',
 'Couple',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Group',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Group',
 'Couple',
 'Solo traveller',
 'Group',
 'Solo traveller',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'People with friends',
 'Couple',
 'Solo traveller',
 'Standard Double Room with Shared Bathroom',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Group',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Duplex Apartment (4 Adults)',
 'Solo traveller',
 'People with friends',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'People with friends',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'People with friends',
 'Group',
 'Group',
 'Double Room',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Holiday Home',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Group',
 'Group',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Group',
 'Solo traveller',
 'Group',
 'Couple',
 'Group',
 'Group',
 'Family with young children',
 'Couple',
 'Standard Studio',
 'Family with young children',
 'Couple',
 'Couple',
 'Family with young children',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Group',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Group',
 'Solo traveller',
 'Couple',
 'Queen Room with Garden View',
 'Group',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Group',
 'Couple',
 'Couple',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Family with young children',
 'Couple',
 'Group',
 'Group',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Standard Double Room',
 'Couple',
 'Group',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Group',
 'Solo traveller',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Group',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Family with young children',
 'Group',
 'Solo traveller',
 'Family with young children',
 'Group',
 'Family with young children',
 'Standard Double Room',
 'Couple',
 'Couple',
 'Couple',
 'Group',
 'Solo traveller',
 'Group',
 'Group',
 'Couple',
 'Solo traveller',
 'Group',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Group',
 'Group',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Group',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Group',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Double Room',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'People with friends',
 'Couple',
 'Couple',
 'Single Room',
 'Family with young children',
 'Solo traveller',
 'Double Room',
 'Group',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Couple',
 'Two-Bedroom Apartment',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Group',
 'Group',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'People with friends',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Group',
 'Couple',
 'Family with young children',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'People with friends',
 'Couple',
 'Couple',
 'People with friends',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Couple',
 'One-Bedroom Apartment',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Family with young children',
 'Couple',
 'Couple',
 'One-Bedroom Apartment',
 'Solo traveller',
 'Group',
 'Group',
 'Couple',
 'Group',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Group',
 'Family with young children',
 'Couple',
 'People with friends',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Leisure trip',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Couple',
 'Family with young children',
 'People with friends',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Leisure trip',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Family with young children',
 'Leisure trip',
 'Group',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Group',
 'Family with young children',
 'Group',
 'Solo traveller',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Studio Apartment with Weekly Housekeeping',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Group',
 'Family with young children',
 'Couple',
 'Couple',
 'Couple',
 'People with friends',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Leisure trip',
 'Studio Apartment with Weekly Housekeeping',
 'Group',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Couple',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Couple',
 'People with friends',
 'Couple',
 'Family with young children',
 'Family with young children',
 'People with friends',
 'Solo traveller',
 'Standard Twin Room',
 'Group',
 'Group',
 'Couple',
 'Couple',
 'People with friends',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Group',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Family with young children',
 'Couple',
 'Group',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Couple',
 'People with friends',
 'Family with young children',
 'Solo traveller',
 'People with friends',
 'Couple',
 'People with friends',
 'People with friends',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'People with friends',
 'Couple',
 'Group',
 'Standard Single Room',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'People with friends',
 'Couple',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Two-Bedroom Apartment',
 'Family with young children',
 'Group',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Standard Double Room',
 'Family with young children',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Group',
 'Couple',
 'Couple',
 'Couple',
 'Standard Twin Room',
 'Solo traveller',
 'Solo traveller',
 'People with friends',
 'Group',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'People with friends',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Group',
 'Couple',
 'Couple',
 'Couple',
 'Group',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'People with friends',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Couple',
 'Family with young children',
 'Family with young children',
 'People with friends',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Group',
 'Solo traveller',
 'Group',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Family with young children',
 'Deluxe Double or Twin Room with Spa Bath',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Double Room',
 'Family with young children',
 'Couple',
 'Couple',
 'Family with young children',
 'Deluxe Twin Room',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Group',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Group',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Group',
 'Couple',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Group',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Group',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Group',
 'Couple',
 'Single Room with Park View',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Group',
 'Couple',
 'Couple',
 'Family with young children',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Group',
 'People with friends',
 'Family with young children',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Family with young children',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Couple',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'One-Bedroom Suite',
 'Couple',
 'Couple',
 'Couple',
 'Group',
 'Couple',
 'Leisure trip',
 'Solo traveller',
 'Solo traveller',
 'Studio Apartment',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Solo traveller',
 'Leisure trip',
 'Group',
 'Couple',
 'Solo traveller',
 'People with friends',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Standard Double Room',
 'Family with young children',
 'Family with young children',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Family with young children',
 'People with friends',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Group',
 'People with friends',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Group',
 'Solo traveller',
 'Couple',
 'Family with young children',
 'Family with young children',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Group',
 'Couple',
 'Couple',
 'Couple',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Couple',
 'People with friends',
 'Solo traveller',
 'Family with young children',
 'Solo traveller',
 'Group',
 'Family with young children',
 'Family with young children',
 'People with friends',
 'Couple',
 'Solo traveller',
 'Solo traveller',
 'Group',
 'Couple',
 ...]

In [314]:
df[["trip_type", "traveller_type", "room_type", "stay_length", "submission_type"]] = split_df[["trip_type", "traveller_type", "room_type", "stay_length", "submission_type"]]

In [315]:
df.shape

(26185, 17)

In [316]:
df.head()

,review_title,hotel_name,avg_rating,nationality,rating,review_text,tags,language,date,year,month,season,trip_type,traveller_type,room_type,stay_length,submission_type
0,Exceptional,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2021-07-11,2021,July,Summer,Business trip,Solo traveller,Junior Suite,Stayed 1 night,Submitted via mobile
1,I highly recommend this b&b! We enjoyed it a lot!,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,en-gb,2019-11-24,2019,November,Autumn,Leisure trip,Couple,Deluxe Suite,Stayed 1 night,Submitted via mobile
2,Exceptional,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,Leisure trip~Couple~Apartment with Sea View~St...,en-gb,2020-01-03,2020,January,Winter,Leisure trip,Couple,Apartment with Sea View,Stayed 6 nights,Submitted via mobile
3,My stay in the house was a experiencing bliss ...,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,Business trip~Solo traveller~Junior Suite~Stay...,en-gb,2019-09-08,2019,September,Autumn,Business trip,Solo traveller,Junior Suite,Stayed 4 nights,Submitted via mobile
4,One bedroom apartment with wonderful view and ...,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,Leisure trip~People with friends~Apartment wit...,en-gb,2019-06-23,2019,June,Summer,Leisure trip,People with friends,Apartment with Sea View,Stayed 4 nights,Submitted via mobile

In [317]:
drop_columns = ['submission_type','tags','room_type','date']
df = df.drop(drop_columns, axis=1)
df.head()

,review_title,hotel_name,avg_rating,nationality,rating,review_text,language,year,month,season,trip_type,traveller_type,stay_length
0,Exceptional,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",en-gb,2021,July,Summer,Business trip,Solo traveller,Stayed 1 night
1,I highly recommend this b&b! We enjoyed it a lot!,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,en-gb,2019,November,Autumn,Leisure trip,Couple,Stayed 1 night
2,Exceptional,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,en-gb,2020,January,Winter,Leisure trip,Couple,Stayed 6 nights
3,My stay in the house was a experiencing bliss ...,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,en-gb,2019,September,Autumn,Business trip,Solo traveller,Stayed 4 nights
4,One bedroom apartment with wonderful view and ...,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,en-gb,2019,June,Summer,Leisure trip,People with friends,Stayed 4 nights

In [318]:
df.info()

<class 'pandas.DataFrame'>
Index: 26185 entries, 0 to 26674
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review_title    26185 non-null  str
 1   hotel_name      26185 non-null  str
 2   avg_rating      26185 non-null  float64
 3   nationality     26185 non-null  str
 4   rating          26185 non-null  float64
 5   review_text     26185 non-null  str
 6   language        26185 non-null  str
 7   year            26185 non-null  str
 8   month           26185 non-null  category
 9   season          26185 non-null  str
 10  trip_type       26185 non-null  str
 11  traveller_type  26185 non-null  str
 12  stay_length     26056 non-null  str
dtypes: category(1), float64(2), str(10)
memory usage: 2.6 MB

In [319]:
df = df.dropna()

In [320]:
df.info()

<class 'pandas.DataFrame'>
Index: 26056 entries, 0 to 26674
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review_title    26056 non-null  str
 1   hotel_name      26056 non-null  str
 2   avg_rating      26056 non-null  float64
 3   nationality     26056 non-null  str
 4   rating          26056 non-null  float64
 5   review_text     26056 non-null  str
 6   language        26056 non-null  str
 7   year            26056 non-null  str
 8   month           26056 non-null  category
 9   season          26056 non-null  str
 10  trip_type       26056 non-null  str
 11  traveller_type  26056 non-null  str
 12  stay_length     26056 non-null  str
dtypes: category(1), float64(2), str(10)
memory usage: 2.6 MB

In [321]:
df["language"].value_counts()

language
en-gb    26056
Name: count, dtype: int64

In [323]:
df = df.drop(['language'], axis=1)
df.head()

,review_title,hotel_name,avg_rating,nationality,rating,review_text,year,month,season,trip_type,traveller_type,stay_length
0,Exceptional,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",2021,July,Summer,Business trip,Solo traveller,Stayed 1 night
1,I highly recommend this b&b! We enjoyed it a lot!,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,2019,November,Autumn,Leisure trip,Couple,Stayed 1 night
2,Exceptional,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,2020,January,Winter,Leisure trip,Couple,Stayed 6 nights
3,My stay in the house was a experiencing bliss ...,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,2019,September,Autumn,Business trip,Solo traveller,Stayed 4 nights
4,One bedroom apartment with wonderful view and ...,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,2019,June,Summer,Leisure trip,People with friends,Stayed 4 nights

## Preprocessing

In [324]:
df.head()

,review_title,hotel_name,avg_rating,nationality,rating,review_text,year,month,season,trip_type,traveller_type,stay_length
0,Exceptional,Villa Pura Vida,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...",2021,July,Summer,Business trip,Solo traveller,Stayed 1 night
1,I highly recommend this b&b! We enjoyed it a lot!,Villa Pura Vida,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,2019,November,Autumn,Leisure trip,Couple,Stayed 1 night
2,Exceptional,Hydro Palace Apartment,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,2020,January,Winter,Leisure trip,Couple,Stayed 6 nights
3,My stay in the house was a experiencing bliss ...,Villa Pura Vida,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,2019,September,Autumn,Business trip,Solo traveller,Stayed 4 nights
4,One bedroom apartment with wonderful view and ...,Hydro Palace Apartment,9.2,South Africa,9.2,The building itself has a very musty smell in ...,2019,June,Summer,Leisure trip,People with friends,Stayed 4 nights

In [325]:
df.to_csv(r'..\data\booking_reviews_cleaned.csv', index=False)