In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/booking_reviews copy.csv')
df.head()

,index,review_title,reviewed_at,reviewed_by,images,crawled_at,url,hotel_name,hotel_url,avg_rating,nationality,rating,review_text,raw_review_text,tags,meta
0,0,Exceptional,11 July 2021,Kyrylo,NaN,"07/20/2021, 01:09:27",https://www.booking.com/reviews/be/hotel/villa...,Villa Pura Vida,https://www.booking.com/hotel/be/villa-pura-vi...,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...","<p class=""review_pos ""><svg aria-label=""Positi...",Business trip~Solo traveller~Junior Suite~Stay...,"{'language': 'en-gb', 'source': 'https://www.b..."
1,1,I highly recommend this b&b! We enjoyed it a lot!,24 November 2019,Dimitri,NaN,"07/20/2021, 01:09:27",https://www.booking.com/reviews/be/hotel/villa...,Villa Pura Vida,https://www.booking.com/hotel/be/villa-pura-vi...,9.7,Belgium,9.0,Very friendly host and perfect breakfast!,"<p class=""review_pos ""><svg aria-label=""Positi...",Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...,"{'language': 'en-gb', 'source': 'https://www.b..."
2,2,Exceptional,3 January 2020,Virginia,NaN,"07/20/2021, 01:09:27",https://www.booking.com/reviews/be/hotel/hydro...,Hydro Palace Apartment,https://www.booking.com/hotel/be/hydro-palace....,9.2,United Kingdom,10.0,It was just what we wanted for a week by the b...,"<p class=""review_neg ""><svg aria-label=""Negati...",Leisure trip~Couple~Apartment with Sea View~St...,"{'language': 'en-gb', 'source': 'https://www.b..."
3,3,My stay in the house was a experiencing bliss ...,8 September 2019,Kannan,NaN,"07/20/2021, 01:09:28",https://www.booking.com/reviews/be/hotel/villa...,Villa Pura Vida,https://www.booking.com/hotel/be/villa-pura-vi...,9.7,Netherlands,10.0,My stay in the house was a experiencing bliss ...,"<p class=""review_pos ""><svg aria-label=""Positi...",Business trip~Solo traveller~Junior Suite~Stay...,"{'language': 'en-gb', 'source': 'https://www.b..."
4,4,One bedroom apartment with wonderful view and ...,23 June 2019,Sue,https://cf.bstatic.com/xdata/images/xphoto/squ...,"07/20/2021, 01:09:28",https://www.booking.com/reviews/be/hotel/hydro...,Hydro Palace Apartment,https://www.booking.com/hotel/be/hydro-palace....,9.2,South Africa,9.2,The building itself has a very musty smell in ...,"<p class=""review_neg ""><svg aria-label=""Negati...",Leisure trip~People with friends~Apartment wit...,"{'language': 'en-gb', 'source': 'https://www.b..."

In [3]:
df.shape

(26675, 16)

In [4]:
df.columns

Index(['index', 'review_title', 'reviewed_at', 'reviewed_by', 'images',
       'crawled_at', 'url', 'hotel_name', 'hotel_url', 'avg_rating',
       'nationality', 'rating', 'review_text', 'raw_review_text', 'tags',
       'meta'],
      dtype='str')

In [5]:
df.describe()

              index    avg_rating        rating
count  26675.000000  26386.000000  26386.000000
mean   13337.000000      8.449242      8.560669
std     7700.553552      0.716427      1.566554
min        0.000000      3.800000      1.000000
25%     6668.500000      8.100000      7.900000
50%    13337.000000      8.500000      9.000000
75%    20005.500000      8.900000     10.000000
max    26674.000000     10.000000     10.000000

In [6]:
df.isnull().sum()

index                  0
review_title           1
reviewed_at          105
reviewed_by          105
images             25737
crawled_at           289
url                  289
hotel_name           289
hotel_url            289
avg_rating           289
nationality          305
rating               289
review_text          289
raw_review_text      473
tags                 473
meta                 473
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26675 entries, 0 to 26674
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            26675 non-null  int64
 1   review_title     26674 non-null  str
 2   reviewed_at      26570 non-null  str
 3   reviewed_by      26570 non-null  str
 4   images           938 non-null    str
 5   crawled_at       26386 non-null  str
 6   url              26386 non-null  str
 7   hotel_name       26386 non-null  str
 8   hotel_url        26386 non-null  str
 9   avg_rating       26386 non-null  float64
 10  nationality      26370 non-null  str
 11  rating           26386 non-null  float64
 12  review_text      26386 non-null  str
 13  raw_review_text  26202 non-null  str
 14  tags             26202 non-null  str
 15  meta             26202 non-null  str
dtypes: float64(2), int64(1), str(13)
memory usage: 48.9 MB

In [8]:
df.nunique(dropna=True).values

array([26675,  8960,  1240,  8566,   755,  3968,  1412,   819,   822,
          42,   163,    36, 18501, 18352,  8082,     1])

In [9]:
df.notnull().sum().values

array([26675, 26674, 26570, 26570,   938, 26386, 26386, 26386, 26386,
       26386, 26370, 26386, 26386, 26202, 26202, 26202])

In [10]:
df.dtypes.astype(str).values

<ArrowStringArray>
[  'int64',     'str',     'str',     'str',     'str',     'str',     'str',
     'str',     'str', 'float64',     'str', 'float64',     'str',     'str',
     'str',     'str']
Length: 16, dtype: str

In [11]:
# comparing review_text with raw_review_text:

df[["review_text", "raw_review_text"]].head(10)

,review_text,raw_review_text
0,"Everything was perfect! Quite, cozy place to r...","<p class=""review_pos ""><svg aria-label=""Positi..."
1,Very friendly host and perfect breakfast!,"<p class=""review_pos ""><svg aria-label=""Positi..."
2,It was just what we wanted for a week by the b...,"<p class=""review_neg ""><svg aria-label=""Negati..."
3,My stay in the house was a experiencing bliss ...,"<p class=""review_pos ""><svg aria-label=""Positi..."
4,The building itself has a very musty smell in ...,"<p class=""review_neg ""><svg aria-label=""Negati..."
5,"Nothing,\n\nBeautiful home! Great room, most c...","<p class=""review_neg ""><svg aria-label=""Negati..."
6,to many messages sending from the owner in the...,"<p class=""review_neg ""><svg aria-label=""Negati..."
7,"Spacious, more than enough rooms, a lot of bat...","<p class=""review_pos ""><svg aria-label=""Positi..."
8,There are no comments available for this review,"<p class=""review_none""><em>There are no commen..."
9,"nothing -- place was perfect,\n\nThis is an ex...","<p class=""review_neg ""><svg aria-label=""Negati..."

In [12]:
# we should keep the review_textfor our analysis

In [13]:
print("Dataset shape:")
print(df.shape)

print("\nColumns:")
for col in df.columns:
    print("-", col)

Dataset shape:
(26675, 16)

Columns:
- index
- review_title
- reviewed_at
- reviewed_by
- images
- crawled_at
- url
- hotel_name
- hotel_url
- avg_rating
- nationality
- rating
- review_text
- raw_review_text
- tags
- meta

In [14]:
exploration_table = pd.DataFrame({
    "dtype": df.dtypes,
    "non_null_count": df.notnull().sum(),
    "null_count": df.isnull().sum(),
    "null_percentage": (df.isnull().mean() * 100).round(2),
    "unique_values": df.nunique()
})

exploration_table

,dtype,non_null_count,null_count,null_percentage,unique_values
index,int64,26675,0,0.00,26675
review_title,str,26674,1,0.00,8960
reviewed_at,str,26570,105,0.39,1240
reviewed_by,str,26570,105,0.39,8566
images,str,938,25737,96.48,755
crawled_at,str,26386,289,1.08,3968
url,str,26386,289,1.08,1412
hotel_name,str,26386,289,1.08,819
hotel_url,str,26386,289,1.08,822
avg_rating,float64,26386,289,1.08,42
nationality,str,26370,305,1.14,163
rating,float64,26386,289,1.08,36
review_text,str,26386,289,1.08,18501
raw_review_text,str,26202,473,1.77,18352
tags,str,26202,473,1.77,8082
meta,str,26202,473,1.77,1

In [15]:
exploration_table.sort_values("null_percentage", ascending=False)

,dtype,non_null_count,null_count,null_percentage,unique_values
images,str,938,25737,96.48,755
raw_review_text,str,26202,473,1.77,18352
meta,str,26202,473,1.77,1
tags,str,26202,473,1.77,8082
nationality,str,26370,305,1.14,163
hotel_name,str,26386,289,1.08,819
crawled_at,str,26386,289,1.08,3968
url,str,26386,289,1.08,1412
rating,float64,26386,289,1.08,36
avg_rating,float64,26386,289,1.08,42
hotel_url,str,26386,289,1.08,822
review_text,str,26386,289,1.08,18501
reviewed_by,str,26570,105,0.39,8566
reviewed_at,str,26570,105,0.39,1240
review_title,str,26674,1,0.00,8960
index,int64,26675,0,0.00,26675

In [16]:
# 1 example of each column: 


for col in df.columns:
    print("=" * 80)
    print(f"COLUMN: {col}")
    print("-" * 80)
    
    sample_values = df[col].dropna().head(3).values
    
    for i, value in enumerate(sample_values, start=1):
        print(f"Sample {i}:")
        print(value)
        print()

================================================================================
COLUMN: index
--------------------------------------------------------------------------------
Sample 1:
0

Sample 2:
1

Sample 3:
2

================================================================================
COLUMN: review_title
--------------------------------------------------------------------------------
Sample 1:
Exceptional

Sample 2:
I highly recommend this b&b! We enjoyed it a lot!

Sample 3:
Exceptional

================================================================================
COLUMN: reviewed_at
--------------------------------------------------------------------------------
Sample 1:
11 July 2021

Sample 2:
24 November 2019

Sample 3:
3 January 2020

================================================================================
COLUMN: reviewed_by
--------------------------------------------------------------------------------
Sample 1:
Kyrylo

Sample 2:
Dimitri

Sample 3:
Virginia

================================================================================
COLUMN: images
--------------------------------------------------------------------------------
Sample 1:
https://cf.bstatic.com/xdata/images/xphoto/square60_ao/69996062.jpg?k=e936f8850d7a2e3e8d4c9b17e552e4d8b346a17a503fd630e364945cfdee1a2c&o=

Sample 2:
https://cf.bstatic.com/xdata/images/xphoto/square60_ao/107140963.jpg?k=225e8d37a851f1692a9bff99fea82fa8d6bfb2b7d505d838fccc0359542afae6&o=

Sample 3:
https://cf.bstatic.com/xdata/images/xphoto/square60_ao/65902050.jpg?k=a53bcda753ebdc613cfad7cd5edf65b8bb6c68ad1b33f8473bf64b955495975e&o=~https://cf.bstatic.com/xdata/images/xphoto/square60_ao/65902054.jpg?k=335c5b0b619f51d7859c19a4d17cc706c80e2dc2cac4268d3cdfe463877555f3&o=~https://cf.bstatic.com/xdata/images/xphoto/square60_ao/65902056.jpg?k=39748581a7b3b9fe0f6eec9d8655fc55ab4fa8068eba2e7641043439b361fbd9&o=~https://cf.bstatic.com/xdata/images/xphoto/square60_ao/65902057.jpg?k=ea694ba12836b77add1b97c6265db224fa016a7ce2b6d425127c6772b3b6c89a&o=

================================================================================
COLUMN: crawled_at
--------------------------------------------------------------------------------
Sample 1:
07/20/2021, 01:09:27

Sample 2:
07/20/2021, 01:09:27

Sample 3:
07/20/2021, 01:09:27

================================================================================
COLUMN: url
--------------------------------------------------------------------------------
Sample 1:
https://www.booking.com/reviews/be/hotel/villa-pura-vida.en-gb.html?label=gen173nr-1BCA0oFUIPdmlsbGEtcHVyYS12aWRhSDNYBGhsiAEBmAEJuAEHyAEN2AEB6AEBiAIBqAIDuALtqdeHBsACAdICJGU0NzQxOGI5LTY1MTEtNDIzOS04MTc4LWFhZWZkNWUwMWU3ONgCBeACAQ;sid=112feb5c809e55c93c7a10cb30d87aae;customer_type=total&hp_nav=0&keep_landing=1&order=featuredreviews&page=1&r_lang=en&rows=75&

Sample 2:
https://www.booking.com/reviews/be/hotel/villa-pura-vida.en-gb.html?label=gen173nr-1BCA0oFUIPdmlsbGEtcHVyYS12aWRhSDNYBGhsiAEBmAEJuAEHyAEN2AEB6AEBiAIBqAIDuALtqdeHBsACAdICJGU0NzQxOGI5LTY1MTEtNDIzOS04MTc4LWFhZWZkNWUwMWU3ONgCBeACAQ;sid=112feb5c809e55c93c7a10cb30d87aae;customer_type=total&hp_nav=0&keep_landing=1&order=featuredreviews&page=1&r_lang=en&rows=75&

Sample 3:
https://www.booking.com/reviews/be/hotel/hydro-palace.en-gb.html?label=gen173nr-1BCA0oFUIMaHlkcm8tcGFsYWNlSDNYBGhsiAEBmAEJuAEHyAEN2AEB6AEBiAIBqAIDuALtqdeHBsACAdICJGVhMGRkOWQ3LTUxOTctNDZjMC1hMDU2LTRlYTIxMTJhMDZhONgCBeACAQ;sid=b24509940b0c16fb9b31db6c116ab216;customer_type=total&hp_nav=0&keep_landing=1&order=featuredreviews&page=1&r_lang=en&rows=75&

================================================================================
COLUMN: hotel_name
--------------------------------------------------------------------------------
Sample 1:
Villa Pura Vida

Sample 2:
Villa Pura Vida

Sample 3:
Hydro Palace Apartment

================================================================================
COLUMN: hotel_url
--------------------------------------------------------------------------------
Sample 1:
https://www.booking.com/hotel/be/villa-pura-vida.en-gb.html?label=gen173nr-1FCA0oFUIPdmlsbGEtcHVyYS12aWRhSDNYBGhsiAEBmAEJuAEHyAEN2AEB6AEB-AELiAIBqAIDuALtqdeHBsACAdICJGU0NzQxOGI5LTY1MTEtNDIzOS04MTc4LWFhZWZkNWUwMWU3ONgCBuACAQ;sid=112feb5c809e55c93c7a10cb30d87aae

Sample 2:
https://www.booking.com/hotel/be/villa-pura-vida.en-gb.html?label=gen173nr-1FCA0oFUIPdmlsbGEtcHVyYS12aWRhSDNYBGhsiAEBmAEJuAEHyAEN2AEB6AEB-AELiAIBqAIDuALtqdeHBsACAdICJGU0NzQxOGI5LTY1MTEtNDIzOS04MTc4LWFhZWZkNWUwMWU3ONgCBuACAQ;sid=112feb5c809e55c93c7a10cb30d87aae

Sample 3:
https://www.booking.com/hotel/be/hydro-palace.en-gb.html?label=gen173nr-1FCA0oFUIMaHlkcm8tcGFsYWNlSDNYBGhsiAEBmAEJuAEHyAEN2AEB6AEB-AELiAIBqAIDuALtqdeHBsACAdICJGVhMGRkOWQ3LTUxOTctNDZjMC1hMDU2LTRlYTIxMTJhMDZhONgCBuACAQ;sid=112feb5c809e55c93c7a10cb30d87aae

================================================================================
COLUMN: avg_rating
--------------------------------------------------------------------------------
Sample 1:
9.7

Sample 2:
9.7

Sample 3:
9.2

================================================================================
COLUMN: nationality
--------------------------------------------------------------------------------
Sample 1:
Poland

Sample 2:
Belgium

Sample 3:
United Kingdom

================================================================================
COLUMN: rating
--------------------------------------------------------------------------------
Sample 1:
10.0

Sample 2:
9.0

Sample 3:
10.0

================================================================================
COLUMN: review_text
--------------------------------------------------------------------------------
Sample 1:
Everything was perfect! Quite, cozy place to relax.

Sample 2:
Very friendly host and perfect breakfast!

Sample 3:
It was just what we wanted for a week by the beach in winter,

Location was fab, apartment quiet and very well-equipped. Spotless clean.

================================================================================
COLUMN: raw_review_text
--------------------------------------------------------------------------------
Sample 1:
<p class="review_pos "><svg aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" height="14" role="img" width="14" viewbox="0 0 32 32" aria-hidden="true" focusable="false">
  <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
</svg><span itemprop="reviewBody">Everything was perfect! Quite, cozy place to relax.</span></p>

Sample 2:
<p class="review_pos "><svg aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" height="14" role="img" width="14" viewbox="0 0 32 32" aria-hidden="true" focusable="false">
  <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
</svg><span itemprop="reviewBody">Very friendly host and perfect breakfast!</span></p>

Sample 3:
<p class="review_neg "><svg aria-label="Negative point" class="bk-icon -fonticon-removecircle review_item_icon" fill="#BDBDBD" height="14" role="img" width="14" viewbox="0 0 32 32" aria-hidden="true" focusable="false"><path d="m16 0c-8.84 0-16 7.16-16 16s7.16 16 16 16 16-7.16 16-16-7.16-16-16-16zm8 17.6h-16v-3.2h16z"></path></svg><span itemprop="reviewBody">It was just what we wanted for a week by the beach in winter</span></p>,<p class="review_pos "><svg aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" height="14" role="img" width="14" viewbox="0 0 32 32" aria-hidden="true" focusable="false">
  <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
</svg><span itemprop="reviewBody">Location was fab, apartment quiet and very well-equipped. Spotless clean.</span></p>

================================================================================
COLUMN: tags
--------------------------------------------------------------------------------
Sample 1:
Business trip~Solo traveller~Junior Suite~Stayed 1 night~Submitted via mobile

Sample 2:
Leisure trip~Couple~Deluxe Suite~Stayed 1 night~Submitted via mobile

Sample 3:
Leisure trip~Couple~Apartment with Sea View~Stayed 6 nights~Submitted via mobile

================================================================================
COLUMN: meta
--------------------------------------------------------------------------------
Sample 1:
{'language': 'en-gb', 'source': 'https://www.booking.com'}

Sample 2:
{'language': 'en-gb', 'source': 'https://www.booking.com'}

Sample 3:
{'language': 'en-gb', 'source': 'https://www.booking.com'}

In [17]:
sample_row = df.iloc[0]

for col in df.columns:
    print("=" * 80)
    print(col)
    print(sample_row[col])

================================================================================
index
0
================================================================================
review_title
Exceptional
================================================================================
reviewed_at
11 July 2021
================================================================================
reviewed_by
Kyrylo
================================================================================
images
nan
================================================================================
crawled_at
07/20/2021, 01:09:27
================================================================================
url
https://www.booking.com/reviews/be/hotel/villa-pura-vida.en-gb.html?label=gen173nr-1BCA0oFUIPdmlsbGEtcHVyYS12aWRhSDNYBGhsiAEBmAEJuAEHyAEN2AEB6AEBiAIBqAIDuALtqdeHBsACAdICJGU0NzQxOGI5LTY1MTEtNDIzOS04MTc4LWFhZWZkNWUwMWU3ONgCBeACAQ;sid=112feb5c809e55c93c7a10cb30d87aae;customer_type=total&hp_nav=0&keep_landing=1&order=featuredreviews&page=1&r_lang=en&rows=75&
================================================================================
hotel_name
Villa Pura Vida
================================================================================
hotel_url
https://www.booking.com/hotel/be/villa-pura-vida.en-gb.html?label=gen173nr-1FCA0oFUIPdmlsbGEtcHVyYS12aWRhSDNYBGhsiAEBmAEJuAEHyAEN2AEB6AEB-AELiAIBqAIDuALtqdeHBsACAdICJGU0NzQxOGI5LTY1MTEtNDIzOS04MTc4LWFhZWZkNWUwMWU3ONgCBuACAQ;sid=112feb5c809e55c93c7a10cb30d87aae
================================================================================
avg_rating
9.7
================================================================================
nationality
Poland
================================================================================
rating
10.0
================================================================================
review_text
Everything was perfect! Quite, cozy place to relax.
================================================================================
raw_review_text
<p class="review_pos "><svg aria-label="Positive point" class="bk-icon -fonticon-plus review_item_icon" fill="#008009" height="14" role="img" width="14" viewbox="0 0 32 32" aria-hidden="true" focusable="false">
  <path d="M32 16c0 8.836-7.162 16-16 16-8.834 0-16-5.74-16-16C0 6.451 7.166 0 16 0c8.838 0 16 7.162 16 16zm-6.4-2.585c0-.369-.031-.616-.4-.616h-5.998V7.018c0-.369-.297-.62-.666-.62h-5.068c-.369 0-.666.251-.666.62v5.781H6.901c-.369 0-.499.247-.499.616v5.118c0 .369.132.666.499.666H12.8v5.833c0 .369.297.565.666.565h5.068c.369 0 .666-.196.666-.565v-5.833h5.998c.369 0 .4-.297.4-.666v-5.118z"></path>
</svg><span itemprop="reviewBody">Everything was perfect! Quite, cozy place to relax.</span></p>
================================================================================
tags
Business trip~Solo traveller~Junior Suite~Stayed 1 night~Submitted via mobile
================================================================================
meta
{'language': 'en-gb', 'source': 'https://www.booking.com'}

In [18]:
# check duplicaate:

print("Full duplicate rows:")
print(df.duplicated().sum())

Full duplicate rows:
0

In [22]:
# for preprocessing, we should keep review_column, review title (perhaps make them into one column?), 
# reviewd_at (for when) , hotel_name, extractfrom meta the language, and drop the source
# drop url 

# Keep: review_text, review_title, reviewd_at, hotel_name, language (from meta dictionary),nationality, rating, avg_rating, tags (what was the trip for),

In [21]:
df.head(1)

,index,review_title,reviewed_at,reviewed_by,images,crawled_at,url,hotel_name,hotel_url,avg_rating,nationality,rating,review_text,raw_review_text,tags,meta
0,0,Exceptional,11 July 2021,Kyrylo,NaN,"07/20/2021, 01:09:27",https://www.booking.com/reviews/be/hotel/villa...,Villa Pura Vida,https://www.booking.com/hotel/be/villa-pura-vi...,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...","<p class=""review_pos ""><svg aria-label=""Positi...",Business trip~Solo traveller~Junior Suite~Stay...,"{'language': 'en-gb', 'source': 'https://www.b..."

In [23]:
df["avg_rating"].describe()

count    26386.000000
mean         8.449242
std          0.716427
min          3.800000
25%          8.100000
50%          8.500000
75%          8.900000
max         10.000000
Name: avg_rating, dtype: float64

In [24]:
# text lenfth exploration -> important for NLP: 
text_cols = ["review_title", "review_text", "raw_review_text", "tags", "meta"]

text_length_summary = []

for col in text_cols:
    if col in df.columns:
        text_data = df[col].fillna("").astype(str)
        
        text_length_summary.append({
            "column": col,
            "empty_count": (text_data.str.strip() == "").sum(),
            "avg_char_length": text_data.str.len().mean().round(2),
            "min_char_length": text_data.str.len().min(),
            "max_char_length": text_data.str.len().max(),
            "avg_word_count": text_data.str.split().str.len().mean().round(2),
            "min_word_count": text_data.str.split().str.len().min(),
            "max_word_count": text_data.str.split().str.len().max(),
        })

text_length_summary = pd.DataFrame(text_length_summary)
text_length_summary

,column,empty_count,avg_char_length,min_char_length,max_char_length,avg_word_count,min_word_count,max_word_count
0,review_title,1,18.98,0,251,3.09,0,47
1,review_text,289,160.17,0,3368,28.21,0,614
2,raw_review_text,473,782.76,0,4392,71.30,0,686
3,tags,473,74.86,0,145,8.47,0,20
4,meta,473,56.97,0,58,3.93,0,4

In [26]:
# lowercase
# dropna

In [27]:
df.head(1)

,index,review_title,reviewed_at,reviewed_by,images,crawled_at,url,hotel_name,hotel_url,avg_rating,nationality,rating,review_text,raw_review_text,tags,meta
0,0,Exceptional,11 July 2021,Kyrylo,NaN,"07/20/2021, 01:09:27",https://www.booking.com/reviews/be/hotel/villa...,Villa Pura Vida,https://www.booking.com/hotel/be/villa-pura-vi...,9.7,Poland,10.0,"Everything was perfect! Quite, cozy place to r...","<p class=""review_pos ""><svg aria-label=""Positi...",Business trip~Solo traveller~Junior Suite~Stay...,"{'language': 'en-gb', 'source': 'https://www.b..."

In [28]:
df["tags"].head()

0    Business trip~Solo traveller~Junior Suite~Stay...
1    Leisure trip~Couple~Deluxe Suite~Stayed 1 nigh...
2    Leisure trip~Couple~Apartment with Sea View~St...
3    Business trip~Solo traveller~Junior Suite~Stay...
4    Leisure trip~People with friends~Apartment wit...
Name: tags, dtype: str

In [29]:
print(df["tags"].iloc[0])

Business trip~Solo traveller~Junior Suite~Stayed 1 night~Submitted via mobile

In [1]:
# exported tags into: type of trip, traveller type, stay length (per night) 
# exported from review_date: Month + Season 
# exported from meta: the language
# multilingual bert for multilingual data (if we have many languages)
# and check how many languaghes there are
# only  eng -> no need for multilingual bert, we can use regular bert for english data


# Pre-processs stage: 
# - Remove language
# lowercase
# Lemmatizer
# tokenizer
# TF IDF
# bow
# transformer -> ready + Fine Tune

In [30]:
print(df["meta"].iloc[0])

{'language': 'en-gb', 'source': 'https://www.booking.com'}